AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: API Sketch
Globals:
  Function:
    Runtime: provided.al2023
    Architectures: 
      - arm64
    MemorySize: 768
    Timeout: 10
Metadata:
  AWS::ServerlessRepo::Application:
    Name: sam-api-sketch
    Description: Sketching out some SAM / API Gateway stuff in Golang
    Author: Aurelia Peters
    SemanticVersion: "1.0.8"
Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value:
      'Fn::GetAtt':
        - HttpApi
        - ApiEndpoint
# Parameters:
#   pJwtAuthorizerAudience:
#     Description: JWT authorizer authorization audience
#     Type: String
#   pJwtAuthorizerDomain:
#     Description: JWT authorizer authorization domain
#     Type: String
Resources:
  HelloLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./cmd/functions/hello
      Handler: bootstrap
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            ApiId: 
              Ref: HttpApi
            Path: /hello/{name}
            Method: GET
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      FailOnWarnings: true
      DefinitionBody: 
      # NB: As of AWS SAM CLI v1.134.0, the API spec *must* be present in the template for this to work
        openapi: 3.0.3
        info:
          version: 1.0.0
          title: API sketch
          description: Sketching out API stuff
        # security:                                                                                                                                                                                                                                                                                   
        #   - JwtAuthorizer: []                 
        paths:
          /hello/{name}:
            get:
              summary: Say hello
              operationId: getHelloName
              responses:
                2XX:
                  description: Says hello
                4XX:
                  description: Error 
              x-amazon-apigateway-integration:
                httpMethod: POST 
                type: aws_proxy
                payloadFormatVersion: "2.0"
                uri: 
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloLambda.Arn}/invocations
        components:
          # Uncomment this, the "security:" section above, and the "pJwtAuthorizer" parameters to use an AWS JWT authorizer (for use with, e.g., Auth0)
          # securitySchemes:                                                                                                                                                                                                                                                                          
          #   JwtAuthorizer:                                                                                                                                                                                                                                                                   
          #     type: "oauth2"                                                                                                                                                                                                                                                                        
          #     flows: {}                                                                                                                                                                                                                                                                             
          #     x-amazon-apigateway-authorizer:                                                                                                                                                                                                                                                       
          #       identitySource: "$request.header.Authorization"                                                                                                                                                                                                                                     
          #       jwtConfiguration:                                                                                                                                                                                                                                                                   
          #         audience:                                                                                                                                                                                                                                                                         
          #           - Fn::Sub: ${pJwtAuthorizerAudience}                                                                                                                                                                                                                                                    
          #         issuer:                                                                                                                                                                                                                                                                           
          #           Fn::Sub: "https://${pJwtAuthorizerDomain}/"                                                                                                                                                                                                                                             
          #       type: "jwt"                
          
        x-amazon-apigateway-request-validators:
          all:
            validateRequestBody: true
            validateRequestParameters: true
          params-only:
            validateRequestBody: false
            validateRequestParameters: true
          body-only:
            validateRequestBody: true
            validateRequestParameters: false